id: "client_3"
server:
  address: "connection-node:12345"
loop:
  amount: 5
  period: "5s"
log:
  level: "INFO"
batch:
  maxAmount: 1500
output:
  dir: "./output"
datasets:
  menuItems: "./datasets/menu_items/menu_items.csv"
  stores: "./datasets/stores/stores.csv"
  transactionItems: "./datasets/transaction_items_example_3/"
  transactions: "./datasets/transactions_example_3/"
  users: "./datasets/users/"
