id: "client_001"
server:
  address: "connection-node:12345"
loop:
  amount: 5
  period: "5s"
log:
  level: "INFO"
batch:
  maxAmount: 50
output:
  dir: "./output"
datasets:
  menuItems: "./datasets/menu_items/menu_items.csv"
  stores: "./datasets/stores/stores.csv"
  transactionItems: "./datasets/transaction_items/"
  transactions: "./datasets/transactions/"
  users: "./datasets/users/"
