id: "client_001"
server:
  address: "host.docker.internal:12345"
loop:
  amount: 5
  period: "5s"
log:
  level: "INFO"
batch:
  maxAmount: 50
output:
  dir: "./output"
datasets:
  menuItems: "./datasets/menu_items/menu_items.csv"
  stores: "./datasets/stores/stores.csv"
  transactionItems: "./datasets/transaction_items/transaction_items_202307.csv"
  transactions: "./datasets/transactions/transactions_202307.csv"
  users: "./datasets/users/users_202307.csv"
