name: tp0
services:
  client:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    volumes:
      - ./config.yaml:/config.yaml 
      - ./datasets:/datasets   
    networks:
      - coffee_net

networks:
  coffee_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
