name: tp0
services:
  client:
    build: .
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    volumes:
      - ./config.yaml:/config.yaml 
      - ./datasets:/datasets   
    networks:
      - coffee_net

networks:
  coffee_net:
    external: true
    name: connection-node_coffee_net
